# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  name "semver"
  desc "A semantic versioning command line utility written in Go."
  homepage "https://github.com/ffurrer2/semver"
  version "2.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  on_macos do
    on_intel do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
      sha256 "ec91a87f32c7e340ac30da184f9b893090545d6c10d8787eafff1cb5eb686277"
    end
    on_arm do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
      sha256 "cd409528e26224d230bb6a0b7df9b8ac08ae44d33f9b80ab0cf78be4c9ae399c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
      sha256 "c702aff55d5c051262d000ed5865566d9fa5e3417493e5301434e59dce2433a8"
    end
    on_arm do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
      sha256 "665aa10e1d2c6977079b4c6f70d4454a26965fc6fe66a4f45ce7597d58a5b11c"
    end
  end

  # No zap stanza required
end
