# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  name "semver"
  desc "A semantic versioning command line utility written in Go."
  homepage "https://github.com/ffurrer2/semver"
  version "2.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  on_macos do
    on_intel do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
      sha256 "998e894ce882b7fbf4ffee8d58ed4e4c533f954e64a8bcfbf0445ba14dd733da"
    end
    on_arm do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
      sha256 "222ec68f91c788fb4f2c163fc161d8867df71044830c0fca8bae025612ceaf1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
      sha256 "e7b6d3163771441331225f24cb61b659d2e07a809be5c5f1a20ff19e53129e25"
    end
    on_arm do
      url "https://github.com/ffurrer2/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
      sha256 "9de32e2c99655b45ded2a4e47733df128a9f1e352bf527fa887b46599a2bdd38"
    end
  end

  # No zap stanza required
end
