# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "A semantic versioning command line utility written in Go."
  homepage "https://github.com/ffurrer2/semver"
  version "1.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ffurrer2/semver/releases/download/v1.1.0/semver_darwin_amd64.tar.gz"
    sha256 "5762e1b07a93f6fce0f97ae071a8d7c58d4bc67e0ff37fdc5277f2dd2e676a0d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ffurrer2/semver/releases/download/v1.1.0/semver_linux_amd64.tar.gz"
    sha256 "7a41e7d03861f1324b9ddae9398b77c5a9b2db1e0325df9701f31f9bcd87ec1f"
  end

  def install
    bin.install "semver"
  end

  test do
    system "#{bin}/semver version"
  end
end
