# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "A semantic versioning command line utility written in Go."
  homepage "https://github.com/ffurrer2/semver"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ffurrer2/semver/releases/download/v2.4.0/semver_2.4.0_darwin_arm64.tar.gz"
      sha256 "c058fb671d0c75b0c265dc68b354845af0c27c84274ddf36e3471de09756d735"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ffurrer2/semver/releases/download/v2.4.0/semver_2.4.0_darwin_amd64.tar.gz"
      sha256 "9a9caf1273b40c53ccda96b22ead4e7312e9108c5d882932e44b67f87fb7b120"

      def install
        bin.install "semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ffurrer2/semver/releases/download/v2.4.0/semver_2.4.0_linux_arm64.tar.gz"
      sha256 "9220cb903d1c98520b9a61bf7c2205d002c795b7096545c58a24eead04488777"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ffurrer2/semver/releases/download/v2.4.0/semver_2.4.0_linux_amd64.tar.gz"
      sha256 "198e5638d7b7043aee9ab9a5f479e7035e0bb1b021c6e2a6ead58444614726e5"

      def install
        bin.install "semver"
      end
    end
  end

  test do
    system "#{bin}/semver version"
  end
end
