name: Test

on:
  push:
    branches:
    - main

jobs:
  darwin-x64-semver:
    name: Test darwin/x64/semver
    runs-on: macos-latest
    steps:
    - name: Test semver installation
      run: |
        brew tap ffurrer2/homebrew-tap
        brew install ffurrer2/tap/semver
        semver version

  linux-x64-semver:
    name: Test linux/x64/semver
    runs-on: ubuntu-latest
    steps:
    - name: Test semver installation
      run: |
        brew tap ffurrer2/homebrew-tap
        brew install ffurrer2/tap/semver
        semver version
